version: "3"
services:
  redis:
    image: redis
  sessions:
    build: ./
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      NODE_ENV: 'development'
      COOKIE_SECRET: 'somesecretvalue'
      COOKIE_EXPIPRE_IN_MIN: 30
      REDIS_PORT: 6379
      REDIS_END_POINT: 127.0.0.1